### PR TITLE
feature: Added in support for Sprig Templates - including support for…

### LINKED ISSUE #29: Expect to filter duplicate commits!
## Expected Behavior
There will be multiple people in the team making changes to the same project, and the same commit will appear. I hope that the same log can be filtered out in the build log.

## Actual Behavior
Repeated submissions appear multiple times

### LINKED ISSUE #73: feature: add sprig functions to templete.FuncMap
fmap @ chglog.go:307 could add [sprig](https://masterminds.github.io/sprig) functions in to allow more per-repo changelog template customization on the user end without code changes.

E.g. `dict`, `get` and `set` would allow me dedup commit lines sharing the same #issue

## Expected Behavior

In `CHANGELOG.tpl.md` I should be able to create new `dict` like
```gotemplate
{{ $commitsByIssue := dict }}
{{ if not get $commitsByIssues .Refs[0].Ref }}
...
{{ set $commitsByIssues . }}
{{ end }}
```

## Actual Behavior

```
panic: template: CHANGELOG.tpl.md:17 function "dict" not defined
```

## Steps to Reproduce (including precondition)

1. Add the above gotemplate snippet ln 20-21 and 24-25 to .chglog/CHANGELOG.tpl.md
2. Run `git-chglog`

## Your Environment

- OS: RHEL7
- git-chglog version: 0.9.1

### PR DESCRIPTION
**Pull request by delmendo**
… v3 of Sprig

## What does this do / why do we need it?

This adds the template methods from Sprig to the git-chglog universe. The sprig library is a common toolkit for templates. I have used it a lot on the helm project for kubernetes.

This this is the first version that will land in this project - I updated to the v3 version of Sprig since that is the current version.

I wanted to be able to deduplicate commit messages as well as do other formatting tasks that ship standard with sprig.

## How this PR fixes the problem?

It just adds on the library and funcationality.

## What should your reviewer look out for in this PR?

This is my first time contributing to a go project of any kind. I was able to get everything to compile and all tests pass on my machine. I'm still unfamiliar with the way things work in goland so please give me any feedback to

## Check lists

* [x ] Test passed
* [x ] Coding style (indentation, etc)

## Additional Comments (if any)

{Please write here}

## Which issue(s) does this PR fix?

fixes #73
fixes #29

### CODE REVIEW

**Comment by talbright** [comment]
@wadackel / @mavogel can one of you guys take a look?

**Review by mavogel — CHANGES_REQUESTED** [review]
Thanks for adding this great library. Could you provide tests (especially for #29)  and a note in the docs that `sprig` is supported? Thank you

**Comment by clok** [comment]
Excited to see Sprig template library come in. I agree with @mavogel feedback. A test and updated docs linking to the Sprig functions doc http://masterminds.github.io/sprig/

To some, tests act as a form of documentation of what is possible. Thank you again for the contribution. Reach out if you would like help as this is your first time contributing to a go project. 🎉

**Comment by talbright** [comment]
> Excited to see Sprig template library come in. I agree with @mavogel feedback. A test and updated docs linking to the Sprig functions doc http://masterminds.github.io/sprig/
> 
> To some, tests act as a form of documentation of what is possible. Thank you again for the contribution. Reach out if you would like help as this is your first time contributing to a go project. 🎉

@delmendo you are almost there, looks like you even have an offer to help with tests 🕺

**Comment by clok** [comment]
This has been releases as a part of the [v0.14.0](https://github.com/git-chglog/git-chglog/releases/tag/v0.14.0) release. Thank you for your contribution!

**Pull request closed without merging**
