### PR TITLE
Cleanup Markdown lint issues and line breaks

### PR DESCRIPTION
**Pull request by khos2ow**
## What does this do / why do we need it?

This PR fixes 

- Markdown lint issues (e.g. extra empty lines)
- Adhere to Semantic line breaks (https://sembr.org/)

## How this PR fixes the problem?

Appease markdown linters.

## What should your reviewer look out for in this PR?

{Please write here}

## Check lists

* [ ] Test passed
* [ ] Coding style (indentation, etc)

## Additional Comments (if any)

{Please write here}

## Which issue(s) does this PR fix?

not applicable.

### CODE REVIEW

**Comment by clok** [comment]
Thanks for cleaning this up. Did you use a tool like [`prettier`](https://prettier.io/)?

For example, it supports markdown linting via:
```
$ prettier --check README.md -w
```

**Comment by khos2ow** [comment]
Nope, manually! I wasn't even aware of such tool as `prettier`! :sweat_smile:

**Comment by clok** [comment]
I didn't realize it supported markdown until recently. So, we are always learning something! Check it out for future work.

**Review by clok — APPROVED** [review]
Thank you for going through these two files manually. It may be worth running them through a tool like `prettier` to see what it says. 

I just wanted to note two things related to markdown. 
1. The template based markdown files we use in the project cannot be run through a linter in my experience. The `{{}}` templating throws off the formatting and results in broken templates if the linter rewrites the file. 
2. We have an outstanding issue that is not related to this particular PR, but reminds me we should look into formatting our output for the changelog in a linter friendly format. See #56

**Review by mavogel — APPROVED** [review]

**Pull request merged**
