### PR TITLE
feat: enable tag_filter_pattern in config options

### LINKED ISSUE #70: feature: tag-filter-pattern as a config option
Not a bug report

### PR DESCRIPTION
**Pull request by Trim21**
## What does this do / why do we need it?

enable tag-filter-pattern in config options

## What should your reviewer look out for in this PR?

if options in config file works and can be overwrited by args

## Check lists

* [X] Test passed
* [X] Coding style (indentation, etc)

## Which issue(s) does this PR fix?

close #70

### CODE REVIEW

**Comment by rohitchawla22** [comment]
@Trim21 Can we merge this PR in? 
We are trying to achieve something similar where we want to generate changelogs separately for versions 2.* and a different one for versions 1.*
As both the versions of our application currently live in the same repository, git-chglog is not able to differentiate between two different versions.
Thanks

**Comment by Trim21** [comment]
It's ready to be merged

**Comment by mithuns** [comment]
Whats blocking this, I think this is a great feature.

**Comment by Trim21** [comment]
@mithuns I guess it's just because nobody is merging pr

**Comment by mithuns** [comment]
Why is the travis-ci not running ?

**Comment by estahn** [comment]
Any update on this? I guess this will also help with monorepos?

**Comment by Trim21** [comment]
Travis is working https://travis-ci.org/git-chglog/git-chglog/jobs/674668727

**Comment by mavogel** [comment]
Thanks @Trim21 ! We gonna fix the ci and release process separately and most probably move to gh-actions in #58

**Pull request merged**
