### PR TITLE
Consistancy in docker image tag

### PR DESCRIPTION
**Pull request by pratikbalar**
## What does this do / why do we need it?

Stay consistent with docker image tag for good practice and standardization.

## How this PR fixes the problem?

-

## What should your reviewer look out for in this PR?

-

## Check lists

* [x] Test passed
* [x] Coding style (indentation, etc)

## Additional Comments (if any)

Stay consistent with docker image tag for good practice and standardization.

## Which issue(s) does this PR fix?

-

### CODE REVIEW

**Comment by mavogel** [comment]
IMHO docker does not prefix the tags with `v`. @clok WDYT?

**Comment by clok** [comment]
> IMHO docker does not prefix the tags with `v`. @clok WDYT?

I'm looking for the thread with @khos2ow where we discussed this. In short, we landed on no leading `v` as general best practices that we've experienced with docker images is that the tags do not contain the leading `v`, just the semantic version name of the tag. 

I'm always open to a discussion if we find a different approach is more generally accepted.

**Comment by pratikbalar** [comment]
I don't want to compare your practices with others but i found many >5K⭐ (new) projects are consistent with their tags throughout their packaging/ecosystem. And many uses just semver.

I'm just proposing tag consistency throughout, let me know your thoughts,

**Comment by mavogel** [comment]
or we could just do both approaches. No problem

**Comment by pratikbalar** [comment]
Then we should go

**Comment by clok** [comment]
@pratikbalar I didn't mean to come off defensive, if that was the case. 

I definitely appreciate your contribution and input here. Fun part of Devops standards is they always seem to evolve. 

I like the idea of doing both. It's just tags and doesn't "cost" anything. The only real issue is the backlog of previous versions.

**Comment by khos2ow** [comment]
You can take a look at https://github.com/git-chglog/git-chglog/issues/132#issuecomment-809744194 and following thread where we decided on tags without leading `v`.

I'm obviously biased, because I proposed it, and the reason was that essentially anything that comes after `:` is a _version_ (in our case even semantic), and annotating it with leading `v`, IMO, is a bit redundant.

At the end of the day, we already have published tags without leading `v` and to not break our compatibility we have to continue to do so. And if we are to publish with `v` we should do that in parallel and as @clok mentioned we need to backport those as well.

Because of this, I'm a bit against of this change. I mean if we were discussing to decide which one to choose in the first place I'd be neutral, but tags without `v` are already out and publicly available and we will end up with identical tags with and without `v`, which I think it's gonna be redundant.

**Comment by pratikbalar** [comment]
I'm agree @khos2ow , backport previous is also concern and anyone using auto image update(like me) with current semver settings they have to change it too to make it compatible with `v` prefix

Thanks you @clok @khos2ow for this conversation and for amazing application, I'm using this for generating change log for each helm chart as a part of ci pipeline stage, and it works as expected 👍🏻🚀

**Pull request closed without merging**
