### PR TITLE
feat: Added in support for Sprig Go Template Functions 

### LINKED ISSUE #29: Expect to filter duplicate commits!
## Expected Behavior
There will be multiple people in the team making changes to the same project, and the same commit will appear. I hope that the same log can be filtered out in the build log.

## Actual Behavior
Repeated submissions appear multiple times

### LINKED ISSUE #73: feature: add sprig functions to templete.FuncMap
fmap @ chglog.go:307 could add [sprig](https://masterminds.github.io/sprig) functions in to allow more per-repo changelog template customization on the user end without code changes.

E.g. `dict`, `get` and `set` would allow me dedup commit lines sharing the same #issue

## Expected Behavior

In `CHANGELOG.tpl.md` I should be able to create new `dict` like
```gotemplate
{{ $commitsByIssue := dict }}
{{ if not get $commitsByIssues .Refs[0].Ref }}
...
{{ set $commitsByIssues . }}
{{ end }}
```

## Actual Behavior

```
panic: template: CHANGELOG.tpl.md:17 function "dict" not defined
```

## Steps to Reproduce (including precondition)

1. Add the above gotemplate snippet ln 20-21 and 24-25 to .chglog/CHANGELOG.tpl.md
2. Run `git-chglog`

## Your Environment

- OS: RHEL7
- git-chglog version: 0.9.1

### PR DESCRIPTION
**Pull request by delmendo**
## What does this do / why do we need it?

This adds the template methods from Sprig to the git-chglog universe. The sprig library is a common toolkit for templates. I have used it a lot on the helm project for kubernetes.

I wanted to be able to deduplicate commit messages as well as do other formatting tasks that ship standard with sprig.

## How this PR fixes the problem?

It just adds on the library and funcationality.

## What should your reviewer look out for in this PR?

This is my first time contributing to a go project of any kind.  I was able to get everything to compile and all tests pass on my machine.  I'm still unfamiliar with the way things work in goland so please give me any feedback to 

## Check lists

* [X ] Test passed
* [X ] Coding style (indentation, etc)

## Additional Comments (if any)

{Please write here}

## Which issue(s) does this PR fix?

fixes #73 
fixes #29

### CODE REVIEW

**Comment by ghostsquad** [comment]
@delmendo can you rebase please?

**Comment by talbright** [comment]
@delmendo this would be super helpful for users...can you clean this up so it can get merged in?

**Comment by delmendo** [comment]
I'll carve out some time today to work on this.

**Comment by delmendo** [comment]
Full disclosure - I know very little go - I only learned enough to modify this package to do most of what I wanted.  I rebased and resubmitted.  When I run the tests locally they pass - but there is something wrong with how the deps are being pulled over and I'm not sure where to start.  If you could give me a pointer in what I'm doing wrong I'd be willing to put some more time in to try to get this to land

**Comment by talbright** [comment]
I do have a suggestion.

The commit that really matters here is only this one: https://github.com/git-chglog/git-chglog/pull/75/commits/5f9300fbeeae1544328081b73a1f54bf2f075971

Try this:

* Pull latest from upstream master into the master branch of your fork. 
* Create a new branch from the master branch of your fork that now has the latest from upstream master.
* In the new branch cherry pick 5f9300fbeeae1544328081b73a1f54bf2f075971 into it.
* Run `go mod tidy`

> go mod tidy ensures that the go.mod file matches the source code in the module. It adds any missing module requirements necessary to build the current module's packages and dependencies, and it removes requirements on modules that don't provide any relevant packages. It also adds any missing entries to go.sum and removes unnecessary entries.


This will give you a cleaner base to work with, and should cleanup any dependency issues 🤞

**Comment by delmendo** [comment]
Ok so it looks like I did a number of other modifications to my version of Chglog ( I needed better handling for squash commits and some other changes  - so after the rebase I didn't think you wanted all that version included. I created a new fork and generated the merge form there so it can be handled cleaner. It looks like Sprig has had a major version update since I did this work so I updated the library to use that so it will be easier to main tain in the future.   

Here is the new pull request - https://github.com/git-chglog/git-chglog/pull/99


let me know if there is anything else I need to do - or if you want the other changes I made to be submitted to the upstream. Glad to see this project is getting love again!

**Comment by talbright** [comment]
Nice 👍 

You should close this to cut down on the noise for the maintainers...

**Pull request closed without merging**
